# Generated by Django 2.2.4 on 2020-01-26 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(default='')),
                ('likes', models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
