# Generated by Django 3.0.2 on 2020-07-05 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200705_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 13, 52, 55, 644990)),
        ),
    ]
