# Generated by Django 3.0.2 on 2020-07-13 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200705_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 2, 54, 64664)),
        ),
    ]
