# Generated by Django 2.2.4 on 2020-01-24 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191103_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 11, 22, 3, 210679)),
        ),
    ]
