# Generated by Django 2.2.4 on 2020-01-26 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200124_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 17, 49, 40, 651979)),
        ),
    ]
