# Generated by Django 2.2.4 on 2020-01-28 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200126_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 15, 57, 34, 545714)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='users_avatars\\default.png', upload_to='users_avatars'),
        ),
    ]
