# Generated by Django 2.2.4 on 2020-01-30 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200128_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 18, 8, 7, 436611)),
        ),
    ]
