# Generated by Django 2.2.4 on 2020-01-31 20:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200130_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 23, 23, 59, 301645)),
        ),
    ]
