# Generated by Django 2.2.4 on 2020-01-31 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200131_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiving_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 23, 43, 17, 430633)),
        ),
    ]
